# Logitech F710
axis_linear: 1  # Forward/Back
scale_linear: 0.7
scale_linear_turbo: 1.5

axis_angular: 2  # Left/Right
scale_angular: -0.7

start_button: 7  # Trigger start
enable_driving: 5 # must continuing press this button to pub vel
enable_turbo_button: -1  # Button 2 aka thumb button

debug_print: true